2024-12-20 18:12:51,837 / WARNING / Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\PythonProjectsForUU\DZ\Module_12\tests_12_4.py", line 24, in test_run
    run_1 = runner.Runner(25)
            ^^^^^^^^^^^^^^^^^
  File "D:\PythonProjectsForUU\DZ\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-20 18:12:51,844 / WARNING / Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PythonProjectsForUU\DZ\Module_12\tests_12_4.py", line 12, in test_walk
    run_1 = runner.Runner('Vasya', -5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjectsForUU\DZ\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
